var mockup = require('bat-ria-tool/mockup');

exports.response = function (path, params) {

    return mockup.ok({
        "id":"1",
        "title":"一汽丰田全系现车限时大惠战",
        "image_default_id":"10",
        "price":"现场公布超值底价",
        "adress":"南宁市白沙大道24号(亭江路口)",
        "created_time":"1451376494",
        "updated_time":"1451376494",
        "valid_status":"0",
        "modified_by":"system",
        "start_time":"1451376494",
        "end_time":"1456848000",
        "tuan_time":"1452924000",
        "tuan_base_num":"16",
        "content":"预付199元抵1000元购车补贴",
        "intention":[
            "皇冠",
            "锐志",
            "卡罗拉",
            "花冠",
            "威驰",
            "普锐斯",
            "卡罗拉双擎",
            "RAV4",
            "普拉多",
            "兰德酷路泽"
        ],
        "agency":"南宁中达丰田4S店",
        "amount":"19900",
        "slogan":"精美车饰、高档行车记录仪、健康枕头，现场好礼不断",
        "page_title":"一汽丰田全系现车限时大惠战",
        "characteristics":[
            {
                "title":"优先提车",
                "content":"当天下单可享受优先提车权，特权保证年前买车先人一步！"
            },
            {
                "title":"全城最低",
                "content":"承诺当日价格全城最低，如有更低价，可立即享受双倍赔付！"
            }
        ],
        "gift":[
            {
                "title":"购车补贴享不停",
                "content":"预付199元可得1000元活动购车补贴（不包含卡罗拉双擎）"
            },
            {
                "title":"签到礼品送送送",
                "content":"缴纳199元意向金，准时到店可获赠活动专属礼，价值888元金猴纳福一尊（限88尊，礼品有限，送完为止）！未缴纳199意向金，准时到店可获赠活动专属礼，U盘或手机支架一份"
            },
            {
                "title":"现场现金一把抓",
                "content":"订车客户可参与现金一把抓活动，一把抓获多少奖多少现金优惠（限三秒内）！"
            },
            {
                "title":"100%购车抽奖礼",
                "content":"一个购车订单可以抽奖一次，100%中奖！奖品有限量版卡罗拉上市纪念车模、折叠自行车、飞利浦音响、行车记录仪、保健枕、保温杯、双层保温野餐包、食用油！"
            },
            {
                "title":"特推车超级大奖",
                "content":"当天订购RAV4送4000元太阳膜、购皇冠送1500元苹果耳机及680元新秀丽背包！"
            }
        ],
        "process":[
            {
                "title":"免费报名",
                "content":"点击'免费报名'"
            },
            {
                "title":"购车礼包",
                "content":"报名承购后即可以获得支付119元意向金抵1000元购车款大礼包"
            },
            {
                "title":"线下活动",
                "content":"在指定活动时间内到合作4s店参加团购活动"
            },
            {
                "title":"现场下定",
                "content":"现场抵消1000元"
            }
        ],
        "share_image_id":"7",
        "coupon_content":[
            "1、团购会现场订车可抵1000元购车款",
            "2、babababababbababababa",
            "3、babababababba"
        ],
        "created_by":"admin_50",
        "coupon_refund":[
            "1、已经缴纳意向金的用户bababa",
            "2、对于已经缴纳异想记但未但与线下活动的用户babababa"
        ],
        "status":"0",
        "tuan_tags":[
            "签到有礼",
            "成交有礼"
        ],
        "coupon_tags":[
            "现场多重优惠",
            "不订车随时退"
        ],
        "coupon_title":"199抵1000元",
        "defaultImage":"/uploadFiles/ce54c9541615d6cfe8221d9205d55894.jpg",
        "shareImage":"/uploadFiles/50becdafda1f41c2f6a409909bffd32f.jpg",
        "num":17,
        "tuanStatus":1,
        "orderId":"137"
    });
};
