/**
 * Created by baba on 16/4/7.
 */
var mockup = require('bat-ria-tool/mockup');

exports.response = function (path, params) {
    return mockup.ok({
            "totalCount":"2",
            "pageNo":1,
            "pageSize":15,
            "orderBy":null,
            "order":null,
            "data":[
                {
                    "id":"40",
                    "exhibition_coupon_activity_id":"2",
                    "exhibition_coupon_id":"5",
                    "user_id":"420",
                    "name":"",
                    "phone":"",
                    "customer_id":"76",
                    "status":"0",
                    "deal_customer_id":"0",
                    "extra":"",
                    "valid_status":"0",
                    "created_time":"1459853575",
                    "updated_time":"1459853575",
                    "created_by":"mall_420",
                    "modified_by":"mall_420",
                    "channel":"20119",
                    "order_id":"1459853575872753",
                    "signupChannel":{
                        "id":"20119",
                        "related_id":"0",
                        "name":"尚格",
                        "type":"3",
                        "valid_status":"0",
                        "created_time":"1459421100",
                        "updated_time":"1459421100",
                        "modified_by":"admin_24",
                        "created_by":"admin_24",
                        "organization_id":"1"
                    },
                    "customer":{
                        "id":"76",
                        "organization_id":"198",
                        "name":"",
                        "phone":"18811695665",
                        "gender":"0",
                        "channel":"20119",
                        "rating":"",
                        "updated_time":"1459853575",
                        "created_time":"1459853575",
                        "valid_status":"0",
                        "modified_by":"mall_420",
                        "created_by":"mall_420",
                        "user_company_id":"0",
                        "user_id":"0",
                        "identification":""
                    },
                    "exhibitionCouponActivity":{
                        "id":"2",
                        "exhibition_coupon_id":"5",
                        "exhibition_id":"1",
                        "organization_id":"36",
                        "extra":"",
                        "valid_status":"0",
                        "created_time":"1459326146",
                        "updated_time":"1459326146",
                        "created_by":"admin_24",
                        "modified_by":"admin_24",
                        "default_image":"/uploadFiles/388bb3e5a968b9fafb9049f3be64791b.png",
                        "share_image":"/uploadFiles/07eeb8b9dc52c63bedf0be2394d02b73.jpg",
                        "activity_title":"南京车展购车礼",
                        "activity_introduction":"车展观众均可领取",
                        "activity_address":"南京车展",
                        "coupon":"10元购电饭煲券",
                        "activity_invitation":"邀请您来领购车礼",
                        "activity_page_title":"来领购车礼吧",
                        "coupon_used_introduction":"均可使用",
                        "coupon_used_detail_introduction":"车展用户均可使用",
                        "activity_start_time":"1459785600",
                        "activity_end_time":"1459795600",
                        "coupon_start_time":"1459785600",
                        "coupon_end_time":"1459785600"
                    }

                },
                {
                    "id":"38",
                    "exhibition_coupon_activity_id":"2",
                    "exhibition_coupon_id":"5",
                    "user_id":"7",
                    "name":"",
                    "phone":"",
                    "customer_id":"74",
                    "status":"0",
                    "deal_customer_id":"0",
                    "extra":"",
                    "valid_status":"0",
                    "created_time":"1459852851",
                    "updated_time":"1459852851",
                    "created_by":"mall_7",
                    "modified_by":"mall_7",
                    "channel":"20122",
                    "order_id":"1459852851866483",
                    "signupChannel":{
                        "id":"20122",
                        "related_id":"165",
                        "name":"刘士云测试车展",
                        "type":"1",
                        "valid_status":"0",
                        "created_time":"1459851213",
                        "updated_time":"1459851213",
                        "modified_by":"admin_164",
                        "created_by":"admin_164",
                        "organization_id":"198"
                    },
                    "customer":{
                        "id":"74",
                        "organization_id":"198",
                        "name":null,
                        "phone":"18511695665",
                        "gender":"0",
                        "channel":"20122",
                        "rating":"",
                        "updated_time":"1459852851",
                        "created_time":"1459852851",
                        "valid_status":"0",
                        "modified_by":"mall_7",
                        "created_by":"mall_7",
                        "user_company_id":"165",
                        "user_id":"0",
                        "identification":""
                    },
                    "exhibitionCouponActivity":{
                        "id":"2",
                        "exhibition_coupon_id":"5",
                        "exhibition_id":"1",
                        "organization_id":"36",
                        "extra":"",
                        "valid_status":"0",
                        "created_time":"1459326146",
                        "updated_time":"1459326146",
                        "created_by":"admin_24",
                        "modified_by":"admin_24",
                        "default_image":"/uploadFiles/388bb3e5a968b9fafb9049f3be64791b.png",
                        "share_image":"/uploadFiles/07eeb8b9dc52c63bedf0be2394d02b73.jpg",
                        "activity_title":"南京车展购车礼",
                        "activity_introduction":"车展观众均可领取",
                        "activity_address":"南京车展",
                        "coupon":"10元购电饭煲券",
                        "activity_invitation":"邀请您来领购车礼",
                        "activity_page_title":"来领购车礼吧",
                        "coupon_used_introduction":"均可使用",
                        "coupon_used_detail_introduction":"车展用户均可使用",
                        "activity_start_time":"1459785600",
                        "activity_end_time":"1459795600",
                        "coupon_start_time":"1459785600",
                        "coupon_end_time":"1459785600"
                    }

                }
            ]
        }

    );

};