/**
 * Created by baba on 16/4/23.
 */

var mockup = require('bat-ria-tool/mockup');

exports.response = function (path, params) {
    return mockup.ok(
        {
            customers: {
                totalCount: "4",
                pageNo: 1,
                pageSize: 15,
                orderBy: null,
                order: null,
                data: [
                    {
                        id: "42",
                        organization_id: "36",
                        name: "钟珍梅",
                        phone: "13265019973",
                        gender: null,
                        channel: "20011",
                        rating: "D",
                        updated_time: "1458813405",
                        created_time: "1458209582",
                        valid_status: "0",
                        modified_by: "admin_63",
                        created_by: "mall_6",
                        user_company_id: "79",
                        user_id: "0",
                        identification: "",
                        owner: {
                            id: "79",
                            username: "lifa",
                            phone1: "18611081833",
                            name: "李发钰"
                        }
                    },
                    {
                        id: "81",
                        organization_id: "198",
                        name: null,
                        phone: "13265019973",
                        gender: "0",
                        channel: "20120",
                        rating: "",
                        updated_time: "1459853893",
                        created_time: "1459853893",
                        valid_status: "0",
                        modified_by: "mall_6",
                        created_by: "mall_6",
                        user_company_id: "0",
                        user_id: "0",
                        identification: "",
                        owner: null
                    },
                    {
                        id: "107",
                        organization_id: "221",
                        name: "ggh",
                        phone: "13265019973",
                        gender: "0",
                        channel: "20140",
                        rating: "",
                        updated_time: "1460966415",
                        created_time: "1460966415",
                        valid_status: "0",
                        modified_by: "mall_6",
                        created_by: "mall_6",
                        user_company_id: "0",
                        user_id: "0",
                        identification: "",
                        owner: null
                    },
                    {
                        id: "108",
                        organization_id: "277",
                        name: "hhh",
                        phone: "13265019973",
                        gender: "0",
                        channel: "20164",
                        rating: "",
                        updated_time: "1460967180",
                        created_time: "1460967180",
                        valid_status: "0",
                        modified_by: "mall_6",
                        created_by: "mall_6",
                        user_company_id: "0",
                        user_id: "0",
                        identification: "",
                        owner: null
                    }
                ]
            },
            tuanOrders: {
                totalCount: "6",
                pageNo: 1,
                pageSize: 15,
                orderBy: null,
                order: null,
                data: [
                    {
                        id: "621",
                        user_id: "6",
                        intention: "车型一,车型二",
                        created_time: "1458209582",
                        updated_time: "1458209681",
                        valid_status: "0",
                        modified_by: "mall_anonymous",
                        tuan_id: "37",
                        amount: "1",
                        status: "2",
                        name: "钟珍梅",
                        phone: "13265019973",
                        payment: "4",
                        serials_number: "2016031721001004960277087105",
                        created_by: "mall_6",
                        signup_channel: "20011",
                        cn: "e77fd5e8",
                        used_channel: "0",
                        pay_time: "1458209681",
                        customer_id: "42",
                        order_id: "1458209582892533",
                        car_buying_way: "1",
                        sign_in_status: "0",
                        car_buying_status: "0",
                        deal_model: "",
                        tuan: {
                            id: "37",
                            title: "一汽丰田全系现车限时大惠战-【钟珍梅】",
                            image_default_id: "164",
                            price: "现场公布超值底价",
                            address: "南宁市白沙大道24号",
                            created_time: "1458208418",
                            updated_time: "1458902097",
                            valid_status: "0",
                            modified_by: "admin_63",
                            start_time: "0",
                            end_time: "1469872560",
                            tuan_time: "1458208380",
                            tuan_base_num: "66",
                            content: "预付199元抵1000元",
                            intention: "车型一,车型二,车型三,车型四",
                            agency: "线下4s店",
                            amount: "1",
                            slogan: "精美车饰",
                            page_title: "一汽丰田全系现车限时大惠战-【钟珍梅】",
                            characteristics: "优先提车:当天下单可享受优先提车权，特权保证年前买车先人一步！ 全城底价:承诺当日价格全城最低，如有更低价，可立即享受双倍赔付！",
                            gift: "购车补贴享不停:预付199元可得1000元活动购车补贴",
                            process: "免费报名:点击“免费报名”，开启底价购车之旅 购车礼包:报名成功后即可获得支付199元意向金抵1000元购车款大礼包(可根据个人情况选择性支付199元意向金，不支付也不会影响活动参与资格 线下活动:在指定活动时间内到合作4s店参加团购活动 现场下定:支付过199元意向金的用户，在活动现场收银处下定即可抵扣1000元购车款",
                            share_image_id: "165",
                            coupon_content: "团购会现场订车可抵1000元购车款",
                            created_by: "admin_63",
                            coupon_refund: "已缴纳意向金的用户可随时发起退款，发起退款后将在3-15个工作日内退回原支付账户。 对于已缴纳意向金但未参与线下活动的用户，本平台会在活动结束后3日内统一退还诚意金。",
                            status: "1",
                            tuan_tags: "签到有礼！,成交有礼！",
                            coupon_tags: "现场多重优惠,不订车随时退",
                            coupon_title: "预付199元意向金可抵1000元购车款",
                            organization_id: "36",
                            theme: "",
                            is_coupon: "1"
                        }
                    },
                    {
                        id: "627",
                        user_id: "6",
                        intention: "车型一",
                        created_time: "1458628088",
                        updated_time: "1458638608",
                        valid_status: "0",
                        modified_by: "admin_63",
                        tuan_id: "40",
                        amount: "0",
                        status: "2",
                        name: "钟珍梅",
                        phone: "13265019973",
                        payment: "0",
                        serials_number: "",
                        created_by: "mall_6",
                        signup_channel: "20011",
                        cn: "2122a1a9",
                        used_channel: "0",
                        pay_time: "0",
                        customer_id: "42",
                        order_id: "1458628088085790",
                        car_buying_way: "3",
                        sign_in_status: "0",
                        car_buying_status: "1",
                        deal_model: "",
                        tuan: {
                            id: "40",
                            title: "魔力橙【钟珍梅】",
                            image_default_id: "174",
                            price: "现场公布超值低价",
                            address: "知春路20号",
                            created_time: "1458627949",
                            updated_time: "1458909301",
                            valid_status: "0",
                            modified_by: "admin_21",
                            start_time: "0",
                            end_time: "1474612140",
                            tuan_time: "1458627900",
                            tuan_base_num: "21",
                            content: "",
                            intention: "车型一,车型二,车型三",
                            agency: "知春路4s",
                            amount: "12300",
                            slogan: "",
                            page_title: "魔力橙【钟珍梅】",
                            characteristics: "优先提车:当天下单可享受优先提车权，特权保证年前买车先人一步！ 全城底价:承诺当日价格全城最低，如有更低价，可立即享受双倍赔付！",
                            gift: "撒旦:阿萨德",
                            process: "免费报名:点击“免费报名”，开启底价购车之旅 购车礼包:报名成功后即可获得支付199元意向金抵1000元购车款大礼包(可根据个人情况选择性支付199元意向金，不支付也不会影响活动参与资格 线下活动:在指定活动时间内到合作4s店参加团购活动 现场下定:支付过199元意向金的用户，在活动现场收银处下定即可抵扣1000元购车款",
                            share_image_id: "175",
                            coupon_content: "团购会现场订车可抵1000元购车款",
                            created_by: "admin_63",
                            coupon_refund: "已缴纳意向金的用户可随时发起退款，发起退款后将在3-15个工作日内退回原支付账户。 对于已缴纳意向金但未参与线下活动的用户，本平台会在活动结束后3日内统一退还诚意金。",
                            status: "2",
                            tuan_tags: "签到有礼,成交有礼",
                            coupon_tags: "现场多重优惠,不订车随时退",
                            coupon_title: "显得更",
                            organization_id: "36",
                            theme: "orange",
                            is_coupon: "1"
                        }
                    },
                    {
                        id: "643",
                        user_id: "6",
                        intention: "ABC",
                        created_time: "1458959998",
                        updated_time: "1458959998",
                        valid_status: "0",
                        modified_by: "mall_6",
                        tuan_id: "53",
                        amount: "199",
                        status: "0",
                        name: "钟珍梅",
                        phone: "13265019973",
                        payment: "0",
                        serials_number: "",
                        created_by: "mall_6",
                        signup_channel: "20011",
                        cn: "",
                        used_channel: "0",
                        pay_time: "0",
                        customer_id: "42",
                        order_id: "1458959998001270",
                        car_buying_way: "2",
                        sign_in_status: "0",
                        car_buying_status: "0",
                        deal_model: "",
                        tuan: {
                            id: "53",
                            title: "测试",
                            image_default_id: "195",
                            price: "厂家现场公布劲爆底价",
                            address: "北京市海淀区知春路48号盈都大厦",
                            created_time: "1458908873",
                            updated_time: "1460982168",
                            valid_status: "0",
                            modified_by: "admin_24",
                            start_time: "0",
                            end_time: "1477560780",
                            tuan_time: "1461932520",
                            tuan_base_num: "10",
                            content: "",
                            intention: "ABC",
                            agency: "知春路4s",
                            amount: "1",
                            slogan: "",
                            page_title: "测试",
                            characteristics: "优先提车:当天下单可享受优先提车权，特权保证年前买车先人一步！ 全城底价:承诺当日价格全城最低，如有更低价，可立即享受双倍赔付！",
                            gift: "哈哈哈:哈哈哈哈哈哈",
                            process: "免费报名:点击“免费报名”，开启底价购车之旅 购车礼包:报名成功后即可获得支付199元意向金抵1000元购车款大礼包(可根据个人情况选择性支付199元意向金，不支付也不会影响活动参与资格 线下活动:在指定活动时间内到合作4s店参加团购活动 现场下定:支付过199元意向金的用户，在活动现场收银处下定即可抵扣1000元购车款",
                            share_image_id: "196",
                            coupon_content: "团购会现场订车可抵1000元购车款",
                            created_by: "admin_63",
                            coupon_refund: "已缴纳意向金的用户可随时发起退款，发起退款后将在3-15个工作日内退回原支付账户。 对于已缴纳意向金但未参与线下活动的用户，本平台会在活动结束后3日内统一退还诚意金。",
                            status: "2",
                            tuan_tags: "签到有礼,成交有礼",
                            coupon_tags: "现场多重优惠,不订车随时退",
                            coupon_title: "预付199元意向金可抵1000元购车款",
                            organization_id: "36",
                            theme: "freshness",
                            is_coupon: "1"
                        }
                    },
                    {
                        id: "644",
                        user_id: "6",
                        intention: "期望车型一",
                        created_time: "1458961524",
                        updated_time: "1458961524",
                        valid_status: "0",
                        modified_by: "mall_6",
                        tuan_id: "39",
                        amount: "0",
                        status: "0",
                        name: "钟珍梅",
                        phone: "13265019973",
                        payment: "0",
                        serials_number: "",
                        created_by: "mall_6",
                        signup_channel: "20011",
                        cn: "",
                        used_channel: "0",
                        pay_time: "0",
                        customer_id: "42",
                        order_id: "1458961524337394",
                        car_buying_way: "1",
                        sign_in_status: "0",
                        car_buying_status: "0",
                        deal_model: "",
                        tuan: {
                            id: "39",
                            title: "丰田抢购会【钟珍梅】",
                            image_default_id: "172",
                            price: "车展现场公布",
                            address: "知春路20号",
                            created_time: "1458621519",
                            updated_time: "1458909281",
                            valid_status: "0",
                            modified_by: "admin_21",
                            start_time: "0",
                            end_time: "1477543260",
                            tuan_time: "1458621480",
                            tuan_base_num: "23",
                            content: "",
                            intention: "期望车型一,期望车型二,期望车型三",
                            agency: "知春路4s",
                            amount: "0",
                            slogan: "",
                            page_title: "丰田抢购会【钟珍梅】",
                            characteristics: "优先提车:当天下单可享受优先提车权，特权保证年前买车先人一步！ 全城底价:承诺当日价格全城最低，如有更低价，可立即享受双倍赔付！",
                            gift: "多重好礼一:多重豪礼内容二",
                            process: "免费报名:点击“免费报名”，开启底价购车之旅 购车礼包:报名成功后即可获得支付199元意向金抵1000元购车款大礼包(可根据个人情况选择性支付199元意向金，不支付也不会影响活动参与资格 线下活动:在指定活动时间内到合作4s店参加团购活动 现场下定:支付过199元意向金的用户，在活动现场收银处下定即可抵扣1000元购车款",
                            share_image_id: "173",
                            coupon_content: "团购会现场订车可抵1000元购车款",
                            created_by: "admin_63",
                            coupon_refund: "已缴纳意向金的用户可随时发起退款，发起退款后将在3-15个工作日内退回原支付账户。 对于已缴纳意向金但未参与线下活动的用户，本平台会在活动结束后3日内统一退还诚意金。",
                            status: "1",
                            tuan_tags: "签到有礼,成交有礼",
                            coupon_tags: "现场多重优惠,不订车随时退",
                            coupon_title: "",
                            organization_id: "36",
                            theme: "green",
                            is_coupon: "1"
                        }
                    },
                    {
                        id: "645",
                        user_id: "6",
                        intention: "车型一",
                        created_time: "1459139951",
                        updated_time: "1459139951",
                        valid_status: "0",
                        modified_by: "mall_6",
                        tuan_id: "48",
                        amount: "0",
                        status: "0",
                        name: "asd",
                        phone: "13265019973",
                        payment: "0",
                        serials_number: "",
                        created_by: "mall_6",
                        signup_channel: "20011",
                        cn: "",
                        used_channel: "0",
                        pay_time: "0",
                        customer_id: "42",
                        order_id: "1459139951077712",
                        car_buying_way: "2",
                        sign_in_status: "0",
                        car_buying_status: "0",
                        deal_model: "",
                        tuan: {
                            id: "48",
                            title: "测试-一汽丰田团购会【钟珍梅】",
                            image_default_id: "188",
                            price: "现场公布",
                            address: "知春路20号",
                            created_time: "1458728263",
                            updated_time: "1458873421",
                            valid_status: "0",
                            modified_by: "admin_63",
                            start_time: "0",
                            end_time: "1479378000",
                            tuan_time: "1458728220",
                            tuan_base_num: "23",
                            content: "",
                            intention: "车型一,车型二,车型三",
                            agency: "知春路4s",
                            amount: "0",
                            slogan: "",
                            page_title: "测试-一汽丰田团购会【钟珍梅】",
                            characteristics: "优先提车:当天下单可享受优先提车权，特权保证年前买车先人一步！ 全城底价:承诺当日价格全城最低，如有更低价，可立即享受双倍赔付！",
                            gift: "标题一:内容一 标题二:内容二",
                            process: "免费报名:点击“免费报名”，开启底价购车之旅 购车礼包:报名成功后即可获得支付199元意向金抵1000元购车款大礼包(可根据个人情况选择性支付199元意向金，不支付也不会影响活动参与资格 线下活动:在指定活动时间内到合作4s店参加团购活动 现场下定:支付过199元意向金的用户，在活动现场收银处下定即可抵扣1000元购车款",
                            share_image_id: "189",
                            coupon_content: "团购会现场订车可抵1000元购车款",
                            created_by: "admin_63",
                            coupon_refund: "已缴纳意向金的用户可随时发起退款，发起退款后将在3-15个工作日内退回原支付账户。 对于已缴纳意向金但未参与线下活动的用户，本平台会在活动结束后3日内统一退还诚意金。",
                            status: "1",
                            tuan_tags: "签到有礼,成交有礼",
                            coupon_tags: "现场多重优惠,不订车随时退",
                            coupon_title: "",
                            organization_id: "36",
                            theme: "green",
                            is_coupon: "0"
                        }
                    },
                    {
                        id: "651",
                        user_id: "6",
                        intention: "",
                        created_time: "1459854659",
                        updated_time: "1459854659",
                        valid_status: "0",
                        modified_by: "mall_6",
                        tuan_id: "55",
                        amount: "0",
                        status: "0",
                        name: "测试",
                        phone: "13265019973",
                        payment: "0",
                        serials_number: "",
                        created_by: "mall_6",
                        signup_channel: "20011",
                        cn: "",
                        used_channel: "0",
                        pay_time: "0",
                        customer_id: "42",
                        order_id: "1459854659722307",
                        car_buying_way: "2",
                        sign_in_status: "0",
                        car_buying_status: "0",
                        deal_model: "",
                        tuan: {
                            id: "55",
                            title: "测试source",
                            image_default_id: "198",
                            price: "现场公布底价",
                            address: "北京市海淀区知春路48号盈都大厦",
                            created_time: "1459327592",
                            updated_time: "1459929919",
                            valid_status: "0",
                            modified_by: "admin_63",
                            start_time: "0",
                            end_time: "1479974880",
                            tuan_time: "1460717880",
                            tuan_base_num: "2",
                            content: "",
                            intention: "",
                            agency: "知春路4s",
                            amount: "0",
                            slogan: "",
                            page_title: "测试source",
                            characteristics: "优先提车:当天下单可享受优先提车权，特权保证年前买车先人一步！ 全城底价:承诺当日价格全城最低，如有更低价，可立即享受双倍赔付！",
                            gift: "",
                            process: "免费报名:点击“免费报名”，开启底价购车之旅 购车礼包:报名成功后即可获得支付199元意向金抵1000元购车款大礼包(可根据个人情况选择性支付199元意向金，不支付也不会影响活动参与资格 线下活动:在指定活动时间内到合作4s店参加团购活动 现场下定:支付过199元意向金的用户，在活动现场收银处下定即可抵扣1000元购车款",
                            share_image_id: "198",
                            coupon_content: "团购会现场订车可抵1000元购车款",
                            created_by: "admin_63",
                            coupon_refund: "已缴纳意向金的用户可随时发起退款，发起退款后将在3-15个工作日内退回原支付账户。 对于已缴纳意向金但未参与线下活动的用户，本平台会在活动结束后3日内统一退还诚意金。",
                            status: "1",
                            tuan_tags: "签到有礼,成交有礼",
                            coupon_tags: "现场多重优惠,不订车随时退",
                            coupon_title: "",
                            organization_id: "36",
                            theme: "default",
                            is_coupon: "0"
                        }
                    }
                ]
            },
            exhibitionCouponOrders: {
                totalCount: "2",
                pageNo: 1,
                pageSize: 15,
                orderBy: null,
                order: null,
                data: [
                    {
                        id: "72",
                        exhibition_coupon_activity_id: "8",
                        exhibition_coupon_id: "1",
                        user_id: "6",
                        name: "ggh",
                        phone: "13265019973",
                        customer_id: "107",
                        status: "1",
                        deal_customer_id: "0",
                        extra: "",
                        valid_status: "0",
                        created_time: "1460966415",
                        updated_time: "1460967259",
                        created_by: "mall_6",
                        modified_by: "mall_6",
                        channel: "20140",
                        order_id: "1460966415787177",
                        payment: "",
                        amount: "1",
                        exhibitionCouponActivity: {
                            id: "8",
                            exhibition_coupon_id: "1",
                            exhibition_id: "1",
                            organization_id: "221",
                            extra: "",
                            valid_status: "0",
                            created_time: "1460107038",
                            updated_time: "1460107038",
                            created_by: "admin_24",
                            modified_by: "admin_24",
                            exhibitionCoupon: {
                                id: "1",
                                exhibition_id: "1",
                                image_default_id: "7",
                                share_image_id: "8",
                                activity_start_time: "1459238757",
                                activity_end_time: "1459238757",
                                coupon_start_time: "1459238757",
                                coupon_end_time: "1559238757",
                                extra: {
                                    activity_title: "2016第九届南京车博会专属购车礼！",
                                    activity_introduction: "车展观众均可领取，每人限领一份，限500份，先到先得",
                                    activity_address: "南京国际博览中心（河西）",
                                    coupon: "10元购电饭煲礼券",
                                    activity_invitation: "邀您来拿购车礼啦！",
                                    activity_page_title: "来领购车礼吧！",
                                    coupon_used_introduction: "车展现场购车用户可凭此券10元领取电饭煲一个",
                                    coupon_used_detail_introduction: "本活动适用于所有参加的2016年第九届南京车博会的购车用户，用户购车后可凭优惠券到车展现场“购车礼兑换处”兑换购车礼，并可免费参加线上抽奖，车展期间每日下午3点定时开奖，奖品丰厚，品牌电冰箱、 微波炉、高档行车记录仪免费拿，如有任何疑问，可咨询4008-955-088"
                                },
                                valid_status: "0",
                                created_time: "1459238757",
                                updated_time: "1459238757",
                                created_by: "a",
                                modified_by: "a",
                                amount: "1"
                            }
                        }
                    },
                    {
                        id: "73",
                        exhibition_coupon_activity_id: "16",
                        exhibition_coupon_id: "1",
                        user_id: "6",
                        name: "hhh",
                        phone: "13265019973",
                        customer_id: "108",
                        status: "0",
                        deal_customer_id: "0",
                        extra: "",
                        valid_status: "0",
                        created_time: "1460967180",
                        updated_time: "1460967180",
                        created_by: "mall_6",
                        modified_by: "mall_6",
                        channel: "20164",
                        order_id: "1460967180469592",
                        payment: "",
                        amount: "1",
                        exhibitionCouponActivity: {
                            id: "16",
                            exhibition_coupon_id: "14",
                            exhibition_id: "1",
                            organization_id: "277",
                            extra: "",
                            valid_status: "0",
                            created_time: "1460187670",
                            updated_time: "1460187670",
                            created_by: "mall-console_anonymous",
                            modified_by: "mall-console_anonymous",
                            exhibitionCoupon: {
                                id: "14",
                                exhibition_id: "1",
                                image_default_id: "1",
                                share_image_id: "1",
                                activity_start_time: "1461859200",
                                activity_end_time: "1462291200",
                                coupon_start_time: "1461859200",
                                coupon_end_time: "1462262400",
                                extra: {
                                    activity_title: "2016第九届南京车博会专属购车礼！",
                                    activity_introduction: "车展观众均可领取，每人限领一份，限500份，先到先得",
                                    activity_address: "南京国际博览中心（河西）",
                                    coupon: "10元购高档健康枕礼券",
                                    activity_invitation: "邀您来拿购车礼啦！",
                                    activity_page_title: "来领购车礼吧！",
                                    coupon_used_introduction: "车展现场购车用户可凭此券10元领取高档健康枕一个",
                                    coupon_used_detail_introduction: " 本活动适用于所有参加“2016年第九届南京车博会”的购车用户，用户购车后可凭优惠券到车展现场“购车礼兑换处”兑换购车礼，并可免费参加线上抽奖，车展期间每日下午3点定时开奖，奖品丰厚，品牌电冰箱、 微波炉、高档行车记录仪免费拿，如有任何疑问，可咨询4008-955-088"
                                },
                                valid_status: "0",
                                created_time: "1461148675",
                                updated_time: "1461148675",
                                created_by: "admin_24",
                                modified_by: "admin_24",
                                amount: "0"
                            }
                        }
                    }
                ]
            }
        }
    );

};