var mockup = require('bat-ria-tool/mockup');

exports.response = function (path, params) {
    return mockup.list(
        [
            {
                id: "37",
                organization_id: "36",
                name: "11",
                phone: "13953561937",
                gender: null,
                channel:  {
                    id: "20011",
                    related_id: "0",
                    name: "测试4S店1",
                    type: "2",
                    valid_status: "0",
                    created_time: "1456820338",
                    updated_time: "1457434719",
                    modified_by: "mall-console_anonymous",
                    created_by: "admin_24",
                    organization_id: "36"
                },
                rating: "A",
                updated_time: "1457518595",
                created_time: "1457349679",
                valid_status: "0",
                modified_by: "admin_79",
                created_by: "mall_380",
                user_company_id: "79",
                owner: {
                    id: "79",
                    username: "lifa",
                    user_info_id: null,
                    phone1: "18611081833",
                    phone2: null,
                    name: "李发钰",
                    group_id: "38",
                    valid_status: "0",
                    password: "ef5401de6db890b7450872a9368d3715",
                    passwd_modified: "1",
                    access_token: null,
                    auth_key: "61UgEX0CmrhofEFD46_ACZEb4EJtfZNm",
                    created_time: "1456823987",
                    updated_time: "1456829232",
                    modified_by: "admin_79",
                    created_by: "admin_24",
                    in_charge: "1",
                    title: "销售总监"
                }
            },
            {
                id: "35",
                organization_id: "36",
                name: "夏盛",
                phone: "18627944388",
                gender: null,
                channel:  {
                    id: "20015",
                    related_id: "74",
                    name: "coco",
                    type: "1",
                    valid_status: "0",
                    created_time: "1456823972",
                    updated_time: "1457434719",
                    modified_by: "mall-console_anonymous",
                    created_by: "admin_24",
                    organization_id: "36"
                },
                rating: "",
                updated_time: "1457434726",
                created_time: "1457265779",
                valid_status: "0",
                modified_by: "mall-console_anonymous",
                created_by: "mall_30",
                user_company_id: "74",
                owner:  {
                    id: "74",
                    username: "coco",
                    user_info_id: null,
                    phone1: "13501290521",
                    phone2: null,
                    name: "coco",
                    group_id: "44",
                    valid_status: "0",
                    password: "e17feea32e06c0548e42c0e4e1affd7e",
                    passwd_modified: "1",
                    access_token: null,
                    auth_key: "5kSHWtT5acDY4DB3w1JtXCYhTegeGane",
                    created_time: "1456823972",
                    updated_time: "1456901431",
                    modified_by: "admin_74",
                    created_by: "admin_24",
                    in_charge: "1",
                    title: "销售主管"
                }
            },
            {
                id: "27",
                organization_id: "36",
                name: "测试发yu",
                phone: "18817555430",
                gender: null,
                channel: {
                    id: "20011",
                    related_id: "0",
                    name: "测试4S店1",
                    type: "2",
                    valid_status: "0",
                    created_time: "1456820338",
                    updated_time: "1457434719",
                    modified_by: "mall-console_anonymous",
                    created_by: "admin_24",
                    organization_id: "36"
                },
                rating: "",
                updated_time: "1457518308",
                created_time: "1457185786",
                valid_status: "0",
                modified_by: "admin_79",
                created_by: "mall_8",
                user_company_id: "79",
                owner: {
                    id: "79",
                    username: "lifa",
                    user_info_id: null,
                    phone1: "18611081833",
                    phone2: null,
                    name: "李发钰",
                    group_id: "38",
                    valid_status: "0",
                    password: "ef5401de6db890b7450872a9368d3715",
                    passwd_modified: "1",
                    access_token: null,
                    auth_key: "61UgEX0CmrhofEFD46_ACZEb4EJtfZNm",
                    created_time: "1456823987",
                    updated_time: "1456829232",
                    modified_by: "admin_79",
                    created_by: "admin_24",
                    in_charge: "1",
                    title: "销售总监"
                }
            },
            {
                id: "13",
                organization_id: "36",
                name: "王肇刚",
                phone: "13810682928",
                gender: null,
                channel: {
                    id: "20020",
                    related_id: "79",
                    name: "李发钰",
                    type: "1",
                    valid_status: "0",
                    created_time: "1456823987",
                    updated_time: "1457434719",
                    modified_by: "mall-console_anonymous",
                    created_by: "admin_24",
                    organization_id: "36"
                },
                rating: "B",
                updated_time: "1457518290",
                created_time: "1456911196",
                valid_status: "0",
                modified_by: "admin_79",
                created_by: "mall_1",
                user_company_id: "79",
                owner: {
                    id: "79",
                    username: "lifa",
                    user_info_id: null,
                    phone1: "18611081833",
                    phone2: null,
                    name: "李发钰",
                    group_id: "38",
                    valid_status: "0",
                    password: "ef5401de6db890b7450872a9368d3715",
                    passwd_modified: "1",
                    access_token: null,
                    auth_key: "61UgEX0CmrhofEFD46_ACZEb4EJtfZNm",
                    created_time: "1456823987",
                    updated_time: "1456829232",
                    modified_by: "admin_79",
                    created_by: "admin_24",
                    in_charge: "1",
                    title: "销售总监"
                }
            },
            {
                id: "7",
                organization_id: "36",
                name: "刘士云",
                phone: "18511695665",
                gender: null,
                channel: {
                    id: "20011",
                    related_id: "0",
                    name: "测试4S店1",
                    type: "2",
                    valid_status: "0",
                    created_time: "1456820338",
                    updated_time: "1457434719",
                    modified_by: "mall-console_anonymous",
                    created_by: "admin_24",
                    organization_id: "36"
                },
                rating: "C",
                updated_time: "1457518416",
                created_time: "1456830855",
                valid_status: "0",
                modified_by: "admin_79",
                created_by: "mall_7",
                user_company_id: "79",
                owner: {
                    id: "79",
                    username: "lifa",
                    user_info_id: null,
                    phone1: "18611081833",
                    phone2: null,
                    name: "李发钰",
                    group_id: "38",
                    valid_status: "0",
                    password: "ef5401de6db890b7450872a9368d3715",
                    passwd_modified: "1",
                    access_token: null,
                    auth_key: "61UgEX0CmrhofEFD46_ACZEb4EJtfZNm",
                    created_time: "1456823987",
                    updated_time: "1456829232",
                    modified_by: "admin_79",
                    created_by: "admin_24",
                    in_charge: "1",
                    title: "销售总监"
                }
            },
            {
                id: "6",
                organization_id: "36",
                name: "廖也",
                phone: "15801509015",
                gender: null,
                channel: {
                    id: "20019",
                    related_id: "78",
                    name: "李永超",
                    type: "1",
                    valid_status: "0",
                    created_time: "1456824180",
                    updated_time: "1457434719",
                    modified_by: "mall-console_anonymous",
                    created_by: "admin_24",
                    organization_id: "36"
                },
                rating: "",
                updated_time: "1457434726",
                created_time: "1456830008",
                valid_status: "0",
                modified_by: "mall-console_anonymous",
                created_by: "mall_3",
                user_company_id: "78",
                owner: {
                    id: "78",
                    username: "liyongchao",
                    user_info_id: null,
                    phone1: "17605365626",
                    phone2: null,
                    name: "李永超",
                    group_id: "44",
                    valid_status: "0",
                    password: "e10adc3949ba59abbe56e057f20f883e",
                    passwd_modified: "1",
                    access_token: null,
                    auth_key: "3rRvsoDdErU3AAvpomYBiAIjn5zwWSPn",
                    created_time: "1456824180",
                    updated_time: "1457341155",
                    modified_by: "admin_78",
                    created_by: "admin_24",
                    in_charge: "0",
                    title: "销售专员"
                }
            },
            {
                id: "5",
                organization_id: "36",
                name: "吴彦祖",
                phone: "13552862513",
                gender: null,
                channel:  {
                    id: "20015",
                    related_id: "74",
                    name: "coco",
                    type: "1",
                    valid_status: "0",
                    created_time: "1456823972",
                    updated_time: "1457434719",
                    modified_by: "mall-console_anonymous",
                    created_by: "admin_24",
                    organization_id: "36"
                },
                rating: "",
                updated_time: "1457434726",
                created_time: "1456828143",
                valid_status: "0",
                modified_by: "mall-console_anonymous",
                created_by: "mall_34",
                user_company_id: "74",
                owner: {
                    id: "74",
                    username: "coco",
                    user_info_id: null,
                    phone1: "13501290521",
                    phone2: null,
                    name: "coco",
                    group_id: "44",
                    valid_status: "0",
                    password: "e17feea32e06c0548e42c0e4e1affd7e",
                    passwd_modified: "1",
                    access_token: null,
                    auth_key: "5kSHWtT5acDY4DB3w1JtXCYhTegeGane",
                    created_time: "1456823972",
                    updated_time: "1456901431",
                    modified_by: "admin_74",
                    created_by: "admin_24",
                    in_charge: "1",
                    title: "销售主管"
                }
            },
            {
                id: "4",
                organization_id: "36",
                name: "陶仕敏",
                phone: "13811626973",
                gender: null,
                channel: - {
                    id: "20019",
                    related_id: "78",
                    name: "李永超",
                    type: "1",
                    valid_status: "0",
                    created_time: "1456824180",
                    updated_time: "1457434719",
                    modified_by: "mall-console_anonymous",
                    created_by: "admin_24",
                    organization_id: "36"
                },
                rating: "C",
                updated_time: "1457434726",
                created_time: "1456827885",
                valid_status: "0",
                modified_by: "mall-console_anonymous",
                created_by: "mall_4",
                user_company_id: "78",
                owner:  {
                    id: "78",
                    username: "liyongchao",
                    user_info_id: null,
                    phone1: "17605365626",
                    phone2: null,
                    name: "李永超",
                    group_id: "44",
                    valid_status: "0",
                    password: "e10adc3949ba59abbe56e057f20f883e",
                    passwd_modified: "1",
                    access_token: null,
                    auth_key: "3rRvsoDdErU3AAvpomYBiAIjn5zwWSPn",
                    created_time: "1456824180",
                    updated_time: "1457341155",
                    modified_by: "admin_78",
                    created_by: "admin_24",
                    in_charge: "0",
                    title: "销售专员"
                }
            }
        ]
    );

};