var mockup = require('bat-ria-tool/mockup');

exports.response = function (path, params) {
    return mockup.ok(
        [
            {
                "order_id":"1451123148521548",
                "status":"3",
                "payment":null,
                "created_time":"1451123148",
                "product":{
                    "id":"41",
                    "name":"福克斯 2013款 两厢经典 1.8L 自动时尚型",
                    "amount":"10680000",
                    "specification":[
                        {
                            "id":"25",
                            "name":"车身颜色",
                            "display_type":"1",
                            "updated_time":"1451048216",
                            "created_time":"1451048216",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"38",
                                "specification_id":"25",
                                "name":"珠光白",
                                "extra":"",
                                "updated_time":"1451048286",
                                "created_time":"1451048286",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        },
                        {
                            "id":"26",
                            "name":"内饰颜色",
                            "display_type":"1",
                            "updated_time":"1451048225",
                            "created_time":"1451048225",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"41",
                                "specification_id":"26",
                                "name":"米色",
                                "extra":"",
                                "updated_time":"1451048320",
                                "created_time":"1451048320",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        },
                        {
                            "id":"27",
                            "name":"提车城市",
                            "display_type":"1",
                            "updated_time":"1451048241",
                            "created_time":"1451048241",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"42",
                                "specification_id":"27",
                                "name":"全国",
                                "extra":"",
                                "updated_time":"1451048349",
                                "created_time":"1451048349",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        }
                    ],
                    "get_car_city":"全国"
                },
                "user_info":{
                    "user_name":"rere",
                    "user_phone":"18611081833"
                },
                "deposit":1,
                "get_car":"到店提车",
                "trade":"线上支付定金，到店支付尾款",
                "get_car_code":"",
                "expire_time":""
            },
            {
                "order_id":"1451357857742348",
                "status":"3",
                "payment":null,
                "created_time":"1451357857",
                "product":{
                    "id":"41",
                    "name":"福克斯 2013款 两厢经典 1.8L 自动时尚型",
                    "amount":"10680000",
                    "specification":[
                        {
                            "id":"25",
                            "name":"车身颜色",
                            "display_type":"1",
                            "updated_time":"1451048216",
                            "created_time":"1451048216",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"38",
                                "specification_id":"25",
                                "name":"珠光白",
                                "extra":"",
                                "updated_time":"1451048286",
                                "created_time":"1451048286",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        },
                        {
                            "id":"26",
                            "name":"内饰颜色",
                            "display_type":"1",
                            "updated_time":"1451048225",
                            "created_time":"1451048225",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"41",
                                "specification_id":"26",
                                "name":"米色",
                                "extra":"",
                                "updated_time":"1451048320",
                                "created_time":"1451048320",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        },
                        {
                            "id":"27",
                            "name":"提车城市",
                            "display_type":"1",
                            "updated_time":"1451048241",
                            "created_time":"1451048241",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"42",
                                "specification_id":"27",
                                "name":"全国",
                                "extra":"",
                                "updated_time":"1451048349",
                                "created_time":"1451048349",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        }
                    ],
                    "get_car_city":"全国"
                },
                "user_info":{
                    "user_name":"lf",
                    "user_phone":"18611081833"
                },
                "deposit":1,
                "get_car":"到店提车",
                "trade":"线上支付定金，到店支付尾款",
                "get_car_code":"",
                "expire_time":""
            },
            {
                "order_id":"1451369805691646",
                "status":"3",
                "payment":null,
                "created_time":"1451369805",
                "product":{
                    "id":"43",
                    "name":"福特新蒙迪欧2.0L GTDi200时尚型",
                    "amount":"17880000",
                    "specification":[
                        {
                            "id":"26",
                            "name":"内饰颜色",
                            "display_type":"1",
                            "updated_time":"1451048225",
                            "created_time":"1451048225",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"40",
                                "specification_id":"26",
                                "name":"黑色",
                                "extra":"",
                                "updated_time":"1451048309",
                                "created_time":"1451048309",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        },
                        {
                            "id":"27",
                            "name":"提车城市",
                            "display_type":"1",
                            "updated_time":"1451048241",
                            "created_time":"1451048241",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"42",
                                "specification_id":"27",
                                "name":"全国",
                                "extra":"",
                                "updated_time":"1451048349",
                                "created_time":"1451048349",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        },
                        {
                            "id":"25",
                            "name":"车身颜色",
                            "display_type":"1",
                            "updated_time":"1451048216",
                            "created_time":"1451048216",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"43",
                                "specification_id":"25",
                                "name":"珍珠白",
                                "extra":"",
                                "updated_time":"1451103503",
                                "created_time":"1451103503",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        }
                    ],
                    "get_car_city":"全国"
                },
                "user_info":{
                    "user_name":"rr",
                    "user_phone":"18611081833"
                },
                "deposit":1,
                "get_car":"到店提车",
                "trade":"线上支付定金，到店支付尾款",
                "get_car_code":"",
                "expire_time":""
            },
            {
                "order_id":"1452656412100775",
                "status":"3",
                "payment":null,
                "created_time":"1452656412",
                "product":{
                    "id":"45",
                    "name":"",
                    "amount":"4890000",
                    "specification":[
                        {
                            "id":"26",
                            "name":"内饰颜色",
                            "display_type":"1",
                            "updated_time":"1451048225",
                            "created_time":"1451048225",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"40",
                                "specification_id":"26",
                                "name":"黑色",
                                "extra":"",
                                "updated_time":"1451048309",
                                "created_time":"1451048309",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        },
                        {
                            "id":"27",
                            "name":"提车城市",
                            "display_type":"1",
                            "updated_time":"1451048241",
                            "created_time":"1451048241",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"42",
                                "specification_id":"27",
                                "name":"全国",
                                "extra":"",
                                "updated_time":"1451048349",
                                "created_time":"1451048349",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        },
                        {
                            "id":"25",
                            "name":"车身颜色",
                            "display_type":"1",
                            "updated_time":"1451048216",
                            "created_time":"1451048216",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"46",
                                "specification_id":"25",
                                "name":"风格红",
                                "extra":"",
                                "updated_time":"1451460159",
                                "created_time":"1451460159",
                                "valid_status":"0",
                                "modified_by":"admin_31"
                            }
                        }
                    ],
                    "get_car_city":"全国"
                },
                "user_info":{
                    "user_name":"vb",
                    "user_phone":"18611081833"
                },
                "deposit":1,
                "get_car":"到店提车",
                "trade":"线上支付定金，到店支付尾款",
                "get_car_code":"",
                "expire_time":""
            },
            {
                "order_id":"1452753015487718",
                "status":"3",
                "payment":null,
                "created_time":"1452753015",
                "product":{
                    "id":"43",
                    "name":"福特新蒙迪欧2.0L GTDi200时尚型",
                    "amount":"17880000",
                    "specification":[
                        {
                            "id":"26",
                            "name":"内饰颜色",
                            "display_type":"1",
                            "updated_time":"1451048225",
                            "created_time":"1451048225",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"40",
                                "specification_id":"26",
                                "name":"黑色",
                                "extra":"",
                                "updated_time":"1451048309",
                                "created_time":"1451048309",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        },
                        {
                            "id":"27",
                            "name":"提车城市",
                            "display_type":"1",
                            "updated_time":"1451048241",
                            "created_time":"1451048241",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"42",
                                "specification_id":"27",
                                "name":"全国",
                                "extra":"",
                                "updated_time":"1451048349",
                                "created_time":"1451048349",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        },
                        {
                            "id":"25",
                            "name":"车身颜色",
                            "display_type":"1",
                            "updated_time":"1451048216",
                            "created_time":"1451048216",
                            "valid_status":"0",
                            "modified_by":"system",
                            "specificationValue":{
                                "id":"43",
                                "specification_id":"25",
                                "name":"珍珠白",
                                "extra":"",
                                "updated_time":"1451103503",
                                "created_time":"1451103503",
                                "valid_status":"0",
                                "modified_by":"system"
                            }
                        }
                    ],
                    "get_car_city":"全国"
                },
                "user_info":{
                    "user_name":"dd",
                    "user_phone":"18611081833"
                },
                "deposit":1,
                "get_car":"到店提车",
                "trade":"线上支付定金，到店支付尾款",
                "get_car_code":"",
                "expire_time":""
            }
        ]
    );

};